name: Sourcegraph TypeScript LSIF Indexer
description: Generate LSIF data from TypeScript source code
author: Sourcegraph
branding:
  icon: code
  color: purple

inputs:
  file:
    description: The output filename (relative to the repository root).
    default: dump.lsif
  project_root: 
    description: The root of the project (where tsconfig.json is located).
    default: .
  flags:
    description: The flags to pass to the indexer.
    default: '-p .'

runs:
  using: docker
  image: Dockerfile
  env:
    OUT: ${{ inputs.file }}
    PROJECT_ROOT: ${{ inputs.project_root }}
    FLAGS: ${{ inputs.flags }}
